### ISSUE TITLE
How to Make Derper Run Behind nginx

### ISSUE THREAD

**Issue by itbencn** [ngc7331/docker-derper#6]
How to make Derper run after nginx as per the question
In most cases, servers do not only allow one 80/443 service, but instead implement multi domain multi service based on nginx reverse proxy
But when I tried to reverse proxy to Derper, it still couldn't run properly

```
version: "3.8"

services:
  derper:
    image: ngc7331/derper:latest
    container_name: derper
    ports:
      - "7001:80/tcp"
      - "7002:443/tcp"
      - "7003:3478/udp"
    environment:
      DERP_HOSTNAME: derp.example.com
      DERP_CERTMODE: manual
    volumes:
      - /path/to/data:/data:rw
      - /path/to/cert:/data/cert:rw
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:rw
    restart: unless-stopped
```

**Comment by ngc7331** [comment]
According to official doc [here](https://github.com/tailscale/tailscale/tree/main/cmd/derper#guide-to-running-cmdderper), derper cannot work behind a reverse proxy.

> The DERP protocol does a protocol switch inside TLS from HTTP to a custom bidirectional binary protocol. It is thus incompatible with many HTTP proxies. Do not put derper behind another HTTP proxy.

You can configure a set of alternative ports using env `DERP_PORT_HTTP/HTTPS/STUN`, expose them directly and configure them in your tailscale ACL rules. Using your 7001/7002/7003 for example:

docker-compose.yaml:
```yaml
services:
  derper:
    image: ngc7331/derper:latest
    container_name: derper
    ports:
      - "7001:7001/tcp"
      - "7002:7002/tcp"
      - "7003:7003/udp"
    environment:
      DERP_PORT_HTTP: 7001
      DERP_PORT_HTTPS: 7002
      DERP_PORT_STUN: 7003
      DERP_HOSTNAME: derp.example.com
      DERP_CERTMODE: manual
    volumes:
      - /path/to/data:/data:rw
      - /path/to/cert:/data/cert:rw
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:rw
    restart: unless-stopped
```

ACL rules (derpMap):
```json
{
  // ... other parts of tailnet policy file
  "derpMap": {
    "Regions": {
      "900": {
        "RegionID": 900,
        "RegionCode": "example",
        "Nodes": [
          {
            "Name": "example",
            "RegionID": 900,
            "HostName": "derp.example.com",
            "DERPPort": 7002,
            "STUNPort": 7003,
          }
        ]
      }
    }
  }
}
```

And you can test your derper by `curl https://derp.example.com:7002`
